#!/bin/bash
# Project to run under
#SBATCH -A SNIC2019-3-453
# Name of the job 
#SBATCH -J Sequencer-train
# name of the output file
#SBATCH --output=seq-train.out
# name of the error file
#SBATCH --error=seq-train.err

# asking for 1 core
#SBATCH -n 1
# the job can use up to 6 hours minutes to run
# this might be reduced for the coderep test wich does not runs test suites
#SBATCH --time=360
#SBATCH --gres=gpu:v100:1,gpuexcl


# run the program
srun $HOME/sequencer/src/Continuous_Learning/continuous-learning-train-and-test.sh
